services:
  fire_ball_user_dev:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
  fire_ball_user:
    container_name: fire_ball_user
    build: .
    ports:
      - "8000:8000"
    env_file: .env

networks:
  default:
    name: docker-network
    external: true