services:
  fire_ball_user:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
  fire_ball_user_pro:
    container_name: fire_ball_user_pro
    build: .
    env_file: .env

networks:
  default:
    name: development
    external: true