services:
  fire_ball_game:
    build: .
    ports:
      - "5001:5001"
    env_file: .env
  fire_ball_game_pro:
    container_name: fire_ball_game_pro
    build: .
    env_file: .env

networks:
  default:
    name: development
    external: true