services:
  fire_ball_game_dev:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/go/src/app
    env_file: .env
  fire_ball_game:
    container_name: fire_ball_game
    build: .
    env_file: .env

networks:
  default:
    name: development
    external: true